### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by bharath-doijode** [xayilmaz/super-app#1]
Hey Xayilmaz, 
Its a great piece of code which renders the mini apps based on the user's choice. 
I have a question here wrt to the dynamic way of rendering. 
Q: When you generate the SuperApp's build for any of the platforms like android (.apk) / iOS (.ipa), Is the Host build contains both of the mini app's code and assets in it? or it is dynamically loaded from other sources not being the part of generated build?

Thanks,
Bharath

**Comment by xayilmaz** [comment]
If I understood your question correctly, we enable the transition to the mini-app with the bundle generated from the mini-projects within the main project. The specific code doesn’t matter in this case. I haven’t tried it, but it would still work if you link any bundle. So, I must generate a new bundle file each time I develop a mini app. 🙂
